name: Webpack/bouncybox

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demos/bouncybox/www
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
  
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build wasm lib with wasm-pack
        run: wasm-pack build --release

      - name: Build site with webpack
        run: |
          npm install
          npx webpack --config webpack.config.js
  
      - name: Archive webpack dist
        uses: actions/upload-artifact@v3
        with:
          name: demo-bouncybox
          path: dist
    
      - name: Deploy webpack dist to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
